
title: Squad GR
tagline: Ο πρώτος Ελληνικός Server στο Squad
email: your-email@example.com
copyright: join<b>squad</b>.gr 2018. Με κάθε επιφύλαξη πνευματικών δικαιωμάτων / All rights Reserved
description: >- # this means to ignore newlines until "baseurl:"
  Ο πρώτος Ελληνικός server για Squad
baseurl: # the subpath of your site, e.g. /blog
url: "http://joinsquad.gr" # the base hostname & protocol for your site, e.g. http://example.com
static: "/static"
twitter_username: jekyllrb
github_username:  hellenic-milsim


# social channels
github: https://github.com/HellenicMilsim/
facebook: https://www.facebook.com/HellenicMilsimCommunity/
youtube: https://www.youtube.com/channel/UCK2vtGqZ3KoEB3SLyY_rOKQ
discord: https://discord.gg/CjQEAc4

# google analytics
ga_id: UA-90955635-3

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - .idea
 - workspace.iml
 - readme.md
